CFLAGS=-O3 -std=c++17 -c
CC=c++

all: Node.o Network.o Network_Dynamics.o Particles.o generate.o error.o agg.o

Node.o:

Network.o:

Network_Dynamics.o:

Particles.o:

generate.o:

error.o:

agg.o:

%.o: %.cpp 
	$(CC) $(CFLAGS) $< 
